INCLUDE(${CMAKE_SOURCE_DIR}/CMake/HandleLibraryTypes.cmake)

SET (XMLLIB_XMLRPCpp_SEARCH_PATH 
	$ENV{XMLRPCPP_ROOT}
	${PROJECT_SOURCE_DIR}/dependencies/
 
	)       


find_path(XMLLIB_XMLRPCpp_INCLUDE_DIR xmlrpc++/XmlRpc.h
  PATHS  ${XMLLIB_XMLRPCpp_SEARCH_PATH}
  PATH_SUFFIXES xmlrpc++ 
                xmlrpc++/include
               

)

FIND_LIBRARY(XMLLIB_XMLRPCpp_LIBRARY_OPTIMIZED
  NAMES xmlrpc
  PATHS ${XMLLIB_XMLRPCpp_SEARCH_PATH}
  PATH_SUFFIXES Release
)
FIND_LIBRARY(XMLLIB_XMLRPCpp_LIBRARY_DEBUG
  NAMES xmlrpc
  PATHS ${XMLLIB_XMLRPCpp_SEARCH_PATH}
  PATH_SUFFIXES Debug
)

MESSAGE("XMLLIB_XMLRPCpp_LIBRARY_DEBUG is ${XMLLIB_XMLRPCpp_LIBRARY_DEBUG}")
MESSAGE("XMLLIB_XMLRPCpp_LIBRARY_OPTIMIZED is ${XMLLIB_XMLRPCpp_LIBRARY_OPTIMIZED}")


HANDLE_LIBRARY_TYPES(XMLLIB_XMLRPCpp)